### ISSUE TITLE
Right Eye lags while Left Eye doesn't.

### ISSUE THREAD

**Issue by zurgeg** [el-dee/panda3d-openvr#1]
I was working on some code, and it appears that on the demo found in minimal the Right Eye is lagging while the left isn't. What could be causing this? Thanks in advance.

**Comment by el-dee** [comment]
Are you using version 0.1.0 or the latest code ? There is a fix in the latest code to disable the default VSync of the graphic driver, otherwise the frames are synced twice, one by SteamVR and one by the driver, and this result in the right eye lagging.

If you are using latest, Could you open Advanced Frame Timing in SteamVR (Main menu -> Developer -> Advanced Frame Timing) and checks that there are no late frame submission and that all the frames are within the 11ms budget ?

**Comment by zurgeg** [comment]
Yep,  just upgraded. I’ll test it.

**Comment by zurgeg** [comment]
Hmm, still happening

**Comment by el-dee** [comment]
Btw, on which platform are you testing, Windows ? MacOS ? Linux ?
 
Could you open Advanced Frame Timing in SteamVR (Main menu -> Developer -> Advanced Frame Timing) and checks that there are no late frame submission and that all the frames are within the 11ms budget ?

If possible, could you add a screenshot of that window ?

**Comment by zurgeg** [comment]
Wait, could it be that my 1050 Ti isn't good enough for my Quest? I'm testing on windows.

**Comment by el-dee** [comment]
No, it should work perfectly fine.

Could you also try and disable VSync in the NVidia Control Panel ?

**Comment by zurgeg** [comment]
Still doesn't work but it appears that everything is over the 11ms budget so...

**Comment by el-dee** [comment]
Ah, sorry, the 1050 Ti is indeed not  VR-ready according to NVidia, though that's weird your right eye is lagging. The effect should be on both eyes.
Could you still share a screenshot of the Timing window ?

**Comment by zurgeg** [comment]
Yeah hold on...

**Comment by zurgeg** [comment]
Hmm, the "everything over budget" problem isn't happening but here is the screenshot:
![frametime](https://user-images.githubusercontent.com/46549042/89224750-034f3a00-d5a7-11ea-9752-19cf84e8ffec.PNG)

**Comment by zurgeg** [comment]
Does this happen for you? If so then it's probably my dead RAM/Mobo sometimes causing weird stuff. I think this because I had an issue with my PC code where I would randomly clip through the floor.

**Comment by zurgeg** [comment]
In case it's helpful, here's a [video I recorded of it](https://youtu.be/6bQEZv6qvzg).
EDIT: Weird, it doesn't seem to happen in VR View...
EDIT2: Deleted a panda3dopenvr I had in my directory and it still happened.

**Comment by el-dee** [comment]
I tested the Ralph demo on Windows with a GTX 2080 and there is no lag at all between the eyes, the frame budget is around 3ms.

I looked at your video but I don't see any lagging problem at all If the problem is a lag between the two eyes, a video of one of the eye won't help. But maybe I don't understand what your problem actually is ?

**Comment by zurgeg** [comment]
Yeah, it doesn’t seem to happen on the video, the lag between eyes is what
I’m talking about. Could my RAM being in the wrong slot on my motherboard.

**Comment by el-dee** [comment]
No, it's purely a performance problem, or there is a misconfiguration somewhere and you still have vsync enabled

**Comment by zurgeg** [comment]
Do you have a screenshot of your graphics settings so I can compare it to mine?
EDIT: A screenshot of mine
![gpu_settings](https://user-images.githubusercontent.com/46549042/89546268-67a21180-d7d2-11ea-9d4e-23597db2fc84.PNG)

**Comment by zurgeg** [comment]
Hold on, should I try upgrading my GPU to a more VR Ready 1660 Ti?

**Comment by el-dee** [comment]
I'm using the factory default NVidia settings, exactly like yours.
If you have the opportunity to try a VR Ready graphic card it would definitively help.

**Comment by zurgeg** [comment]
Great, I’ll get back to you once I get one!

**Comment by zurgeg** [comment]
I got another video of it, it's attached. This one has both eyes.
[Videos for Debugging.zip](https://github.com/el-dee/panda3d-openvr/files/5051262/Videos.for.Debugging.zip)
It's in zip because GitHub won't let me upload the video file.

**Comment by zurgeg** [comment]
After checking on a GTX 1650 it's still there (though note that this was on a different machine with which I did not check the settings for).

**Comment by el-dee** [comment]
That's weird. Could you check the the vsync is not forced on in the Nvidia settings, and could you get a screenshot or a video of the advanced frame timing window when the problem occurs ? Without that I can not see if it's due to a bad synchro, too much time spend rendering the scene, an offset between the rendering, ...

**Comment by zurgeg** [comment]
Yep! I'll have to get their permission though. For now, I do have a friend who has an RTX 2060 which should be good.

**Comment by zurgeg** [comment]
Well, I received my RTX 2060 and tried. I found what the problem is, the Panda in the demo is sometimes moving around randomly, but only in one eye. Do you know what the fix for this could be? Thanks.

**Comment by el-dee** [comment]
In the current implementation, the left eye texture and the right eye texture are submitted sequentially to the compositor. What could happen is that something is causing delays and when the right eye is submitted the allocated time is already elapsed and the right eye is used to render a new frame, no longer in sync with the left eye... 

I may sound insistent, but could you send a capture of the "advanced frame timing window" while the problem is occurring ? Without that I will never be able to understand how the frames are scheduled"ruled and what is the root cause of the problem.

**Comment by zurgeg** [comment]
Yep! No problem.

EDIT: Could we create a Discord Server for this (as in general support)? I feel like that would be easier to debug if we did.

**Comment by zurgeg** [comment]
Sorry for the late response, here is the advanced frame timing window:

https://youtu.be/b48eDKus0M0

**Comment by zurgeg** [comment]
Hey, @el-dee are you using Single Pass rendering in this module, I get the same effect as in this Unity3D forum post: https://forum.unity.com/threads/right-eye-goes-wonky-when-set-to-singlepass-rendering-vive-steamvr.457426/
The most notable part is:
"Right eye looks a little off", which is definitely what I am experiencing here...
Can you try using Multi-pass?
EDIT: Yet another Unity Forum post describing this:
https://forum.unity.com/threads/jittery-motion-on-oculus-quest.683704/
While browsing the answers, I found something interesting:
"Sounds like some general desync issue rather than something related to the Quest specifically."
Could a similar desync issue be occurring here?

I will note that while these are Unity Forum posts, they all have a similar problem to this one.

**Comment by zurgeg** [comment]
Hold on, could it have to do with the refresh rate of the Quest? I read somewhere that weird things happen if the refresh rate isn't right...

**Comment by el-dee** [comment]
I looked at your video capture, and if it's actually done while you saw stuttering with the right eye, there are no timing or budget issue at all.

So, it's possible that the issue is due to the sensitivity of the quest regarding the refresh rate. The current implementation is actually a multipass implementation (this is the simplest and most straightforward implementation). "Simple pass" are a bunch of optimization to not perform some steps twice, but it's not relevant here.

In my todo list there is a modification to send the both eye data at the same time instead of sequentially, perhaps the Quest is sensitive to that and sending both eye at the same time will solve the issue.

**Comment by zurgeg** [comment]
Hmm, I'll look at the way Oculus Link works...
Also, it would be helpful for future debugging to create a Discord Server for support since a lot of screenshots/videos are needed to be sent over.
EDIT: @el-dee Looked at the pipeline for Oculus Link, it looks like it **needs** them both at the same time or else sync problems happen...

**Comment by zurgeg** [comment]
@el-dee I started the modification for the eye data with PR #5, need some help with replacing the right eye's call to `self.right_cb` though.

**Comment by el-dee** [comment]
I had some time to look at the problem, and there is an obvious bug in the code, the right eye is submitted when the left eye is rendered and vice-versa ! This is not a problem as the texture themselves are not swapped but it's when the right eys is submitted that the compositor knows the frame can be rendered in the HMD.

This explain why there is a delay between the eyes on the Oculus as there is a delay of about a full frame between the left eye submission and the right eye submission.

**Comment by zurgeg** [comment]
Well, unfortunately I can’t test because my Quest broke. If Oculus fixes
their software, I’ll be glad to test!

**Comment by el-dee** [comment]
I'm sorry to hear that :( I made the modifications then and pushed them on the main branch, you can test it when your Quest is up again (hopefully soon)

**Comment by zurgeg** [comment]
OK, My quest is back and functioning. I will install the master branch.

**Comment by zurgeg** [comment]
It's finally patched in V0.1.3, thanks for the help @el-dee!
UPDATE: I have gone ahead to allow the user to enable and disable "verbose mode"/print statements

**Comment by el-dee** [comment]
> It's finally patched in V0.1.3, thanks for the help @el-dee!

Thank you for the feedback, I will release v0.1.3 asap :)

**Comment by zurgeg** [comment]
Also, for general debugging/contributions, it would be helpful if we could create a Discord server.

**Comment by el-dee** [comment]
I will probably create one next week with a channel for panda3d-openvr
