### ISSUE TITLE
Unable to read VR Path Registry

### ISSUE THREAD

**Issue by DiamondsBattle** [el-dee/panda3d-openvr#16]
Hello,
While trying to use this, I get an `Unable to read VR Path Registry` error.
This maybe because I am using Ursina Engine, but since it's based on Panda3D and that other P3D tools work, I doubt it's that.
How can I fix this ? I have tried making the file empty, but no appealing changes.

Full error :
```
  File "C:\Users\***\Downloads\zuiahzgutzgyahz.py", line 8, in <module>
    r.init()
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\p3dopenvr\p3dopenvr.py", line 159, in init
    self.vr_system = openvr.init(openvr.VRApplication_Scene)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\openvr\__init__.py", line 7170, in init
    initInternal2(applicationType, pStartupInfo)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\openvr\__init__.py", line 7302, in initInternal2
    openvr.error_code.InitError.check_error_value(error.value)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\openvr\error_code\__init__.py", line 23, in check_error_value
    raise error_class(error_value, message)
openvr.error_code.InitError_Init_PathRegistryNotFound
Unable to read VR Path Registry from C:\Users\***\AppData\Local\openvr\openvrpaths.vrpath
```
Thanks

**Comment by el-dee** [comment]
That's weird, this file should exist ! It is created by SteamVR when installed. It actually tells libopenvr where the OpenVR implementation resides (in this case SteamVR).

On my machine the content of this file is :
<pre>
{
	"config" : 
	[
		"C:\\Program Files (x86)\\Steam\\config"
	],
	"external_drivers" : null,
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"C:\\Program Files (x86)\\Steam\\logs"
	],
	"runtime" : 
	[
		"C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR"
	],
	"version" : 1
}
</pre>

But before just copying it, I would suggest first to check that SteamVR is correctly installed and running.

**Comment by zurgeg** [comment]
This happened to me once, turns out I had deleted it to test something, I simply reinstalled SteamVR and it worked.
The error is quite vague, as it can also indicate an error reading the file, e.x., not enough permissions. Check if:
1. That file exists
2. You can read from it
3. You have SteamVR (or OpenComposite) installed properly.

Additionally, file I/O (while I assume it's the same in Ursina, it's a good thing to check) can be weird in some game engines. Check that Ursina isn't running off a resource pack file or anything like that,

Also, in your question, you state "I have tried making the file empty". Does this mean the file didn't exist in the first place? If you have SteamVR installed in the default location, iirc Steam moves OpenVR data when you install SteamVR to a different directory.

Hope this helps!

**Comment by DiamondsBattle** [comment]
Okay, thanks, I'm going to try re-install SteamVR, and I will let you know.

**Comment by el-dee** [comment]
I'm closing this. Feel free to reopen if you still encounter problems.
