### ISSUE TITLE
upgrade to pyopenxr?

### ISSUE THREAD

**Issue by kukulski** [el-dee/panda3d-openvr#17]
from pyopenvr github: 
DEPRECATION NOTICE
Our upstream SDK OpenVR is no longer being updated. Everyone is switching to OpenXR instead. We are working on similar bindings for OpenXR at https://github.com/cmbruns/pyopenxr

**Comment by ArachnidAbby** [comment]
If they arent currently going to update this package I may try to take a stab at this myself and then submit a pull request. If that doesnt get accepted then I will probably just make a fork of this.

So if any devs are reading this: are you guys currently working on this or would it be cool for me to take a stab at it?

**Comment by el-dee** [comment]
OpenXR implementation of SteamVR on Linux is still crippled with bugs that make it almost unusable (and make development a nightmare as it sometimes results in X Server crash).

That said, I believe Monado is getting quite stable and could be used for testing (and there is still the possibility to test on Windows...) and I could give it another go at it.

There are probably a couple of thing to change in the architecture of the code, but first I must verify that Panda3D offer the hooks to bind the swapchain image to a framebuffer created by Panda3D, otherwise it would require modifications in the Panda3D source code.

**Comment by ArachnidAbby** [comment]
@el-dee thanks for the response and information.

oh also:
Thanks for making this package!

**Comment by el-dee** [comment]
I could make good progress lately and I managed to make Panda3D render into an OpenXR swapchain and get the result on my HMD.
I still have to integrate projection, poses management, actions, ...; but I believe the majors issues have been taken care of.

**Comment by panmarco83** [comment]
> 

So, what happened ?
Did this continue to be crippled ?
Should this be ported to Monado ?

**Comment by sbrodeur** [comment]
I'm doing similar work and I'm also interested in any progress to using OpenXR rather than OpenVR. I'm currently using Monado as the runtime.

**Comment by el-dee** [comment]
SteamVR usability has (slightly) improved, but the port to OpenXR has been on hold as I am focusing on my main project (which will need OpenXR in the future, but not for the upcoming release).

What I could do is finish and release the core part of the new library, mainly to support basic rendering, HMD, and hopefully poses; and defer the more complex features, like skeletons, trackers and so on.

**Comment by el-dee** [comment]
I finalized and pushed a first version of the new library integrating OpenXR with Panda3D : https://github.com/el-dee/panda3d-openxr

 Basic rendering is supported as well as hand positions. Action set and skeleton support will done later. Also I still need to test it on other platforms and OpenXR runtimes.

Once it is stable, I will deprecate this library.
