### ISSUE TITLE
With MSAA 4, left eye jumps around

### ISSUE THREAD

**Issue by zurgeg** [el-dee/panda3d-openvr#8]
Same thing as in my other issue...

**Comment by el-dee** [comment]
That's weird because the textures are now submitted almost at the same time. What could happens is that the blitting required by the MSAA add too much a delay for the Oculus and we end up again with the old issue...

Do you see any framedrop in the frame timeline of SteamVR or does pstats shows high drawing time ?

**Comment by zurgeg** [comment]
@el-dee I will take a look at it later.

**Comment by zurgeg** [comment]
@el-dee So it seems like this issue still happens on a Vive?

**Comment by el-dee** [comment]
I don't have any issues with my Vive, do you have the problem with one of the samples or with our own app ?

**Comment by zurgeg** [comment]
With the Ralph Sample, I wonder if it's overhead from Python/it's running on my 1050 Ti somehow

**Comment by el-dee** [comment]
I have added the hidden area mesh to discard invisible pixels and improve the fill rate, this should help a bit.
